spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # config-location用于指定mybatis配置文件位置, 推荐将mybatis所有配置都写在全局配置文件的mybatis.configuration中,可省略mybatis的xml配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis原配置文件中的配置项
    map-underscore-to-camel-case: true  # 开启驼峰命名映射, 即数据库字段下划线可映射驼峰命名属性

server:
  port: 8005